spring.application.name=AdmissionWebsite

# db config...
<<<<<<< HEAD
spring.datasource.url=jdbc:sqlserver://studentmanagement.mssql.somee.com;databaseName=studentmanagement;encrypt=true;trustServerCertificate=true;
spring.datasource.username=yash_khandaska_SQLLogin_1
spring.datasource.password=jip4jmmj5q
=======
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
>>>>>>> c0b87e1d92dbb4c8d65018853896c1e861cda9f6
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.SQLServer2016Dialect
spring.jpa.hibernate.ddl-auto = update

# Email Configration Properties.

spring.mail.default-encoding=UTF-8
spring.mail.host=smtp.gmail.com
<<<<<<< HEAD
spring.mail.username=yashkhandaskar56@gmail.com
spring.mail.password=yeyi sndm oboh huwb
=======
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
>>>>>>> c0b87e1d92dbb4c8d65018853896c1e861cda9f6
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.test-connection=false
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Stripe pyment configration

<<<<<<< HEAD
stripe.secretKey=sk_test_51RhlcTFMYHH1zHB8mhtc90A3xhB18yjbiCxDJMBOZWfekZL5PrP1JSByBC71sfdXX2rsTwMdX5XtbT0oYYbXlldm00nP7TXwHx
=======
stripe.secretKey=${STRIPE_SECRET_KEY}
>>>>>>> c0b87e1d92dbb4c8d65018853896c1e861cda9f6

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

server.max-http-header-size=65536
server.tomcat.max-http-form-post-size=50MB
server.tomcat.max-swallow-size=50MB




