spring.application.name=AdmissionWebsite

# db config...
spring.datasource.url=jdbc:sqlserver://studentmanagement.mssql.somee.com;databaseName=studentmanagement;encrypt=true;trustServerCertificate=true;
spring.datasource.username=yash_khandaska_SQLLogin_1
spring.datasource.password=jip4jmmj5q
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.SQLServer2016Dialect
spring.jpa.hibernate.ddl-auto = update

# Email Configration Properties.

spring.mail.default-encoding=UTF-8
spring.mail.host=smtp.gmail.com
spring.mail.username=yashkhandaskar56@gmail.com
spring.mail.password=yeyi sndm oboh huwb
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.test-connection=false
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Stripe pyment configration

stripe.secretKey=sk_test_51RhlcTFMYHH1zHB8mhtc90A3xhB18yjbiCxDJMBOZWfekZL5PrP1JSByBC71sfdXX2rsTwMdX5XtbT0oYYbXlldm00nP7TXwHx

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

server.max-http-header-size=65536
server.tomcat.max-http-form-post-size=50MB
server.tomcat.max-swallow-size=50MB




